# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 05:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SavingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CurrencyType')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 8, 5, 22, 50, 328434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='cause',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Cause'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='saving_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SavingBox'),
            preserve_default=False,
        ),
    ]
