# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160508_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
