# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 21:02
from __future__ import unicode_literals

import uuid

from django.db import migrations


def gen_account_uuid(apps, schema_editor):
    """
    Generate UUIDs for existing accounts.
    """
    Account = apps.get_model('core', 'Account')
    
    for account in Account.objects.all():
        account.uuid = uuid.uuid4()
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_account_uuid),
    ]
