# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160509_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
