# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160512_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
