# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160512_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='typee',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('EXTRACTION', 'EXTRACTION')], max_length=256),
        ),
    ]
