# -*- coding: utf-8 -*-
# Generated by me on 2016-05-27 20:50
from __future__ import unicode_literals

from django.db import migrations

from .. import constants


def update(apps, schema_editor):
    Move = apps.get_model('core', 'Move')
    
    for move in Move.objects.all():
        move.typee = constants.MoveType(int(move.typee)).name
        move.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160527_1956'),
    ]

    operations = [
        migrations.RunPython(update),
    ]
